[package]
name = "starlink-grpc-client"
version = "0.4.1"
authors = ["Andy Wright <andywwright@icloud.com>"]
edition = "2021"
description = "A safe, async, type-safe client for querying Starlink Gen 3 Dishy via gRPC."
license = "MIT"
repository = "https://github.com/andywwright/starlink-grpc-client"
documentation = "https://docs.rs/starlink-grpc-client"
homepage = "https://github.com/andywwright/starlink-grpc-client"
readme = "README.md"

[features]
# by default, we do NOT regenerate protos (no protoc needed)
default = []
# to force proto regen into proto_bindings, run with `--features build-protos`
# use vendored-protoc if you want the vendored protoc binary (auto-enabled with build-protos)
build-protos = ["vendored-protoc"]
vendored-protoc = ["dep:protoc-bin-vendored"]

[dependencies]
tokio = { version = "1.45", features = ["full"] }
tonic = { version = "0.14", features = ["transport"] }
prost = "0.14"
prost-types = { version = "0.14" }
prost-wkt = "0.7"
prost-wkt-types = { version = "0.7", features = ["schemars"] }
tonic-prost = "0.14"
thiserror = "2.0"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
schemars = "1"

[build-dependencies]
tonic-prost-build = "0.14"
prost-build = "0.14"
prost-wkt-build = "0.7"
protoc-bin-vendored = { version = "3", optional = true }
