// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TimestampInfo {
    #[prost(enumeration = "Epoch", tag = "1")]
    pub epoch: i32,
    #[prost(int64, tag = "2")]
    pub nanoseconds: i64,
}
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Epoch {
    Unix = 0,
    Gps = 1,
}
impl Epoch {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unix => "UNIX",
            Self::Gps => "GPS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNIX" => Some(Self::Unix),
            "GPS" => Some(Self::Gps),
            _ => None,
        }
    }
}

# [allow (dead_code)] const _ : () = { use :: prost_wkt :: typetag ; # [typetag :: serde (name = "type.googleapis.com/SpaceX.API.Telemetron.Public.Common.TimestampInfo")] impl :: prost_wkt :: MessageSerde for TimestampInfo { fn package_name (& self) -> & 'static str { "SpaceX.API.Telemetron.Public.Common" } fn message_name (& self) -> & 'static str { "TimestampInfo" } fn type_url (& self) -> & 'static str { "type.googleapis.com/SpaceX.API.Telemetron.Public.Common.TimestampInfo" } fn new_instance (& self , data : Vec < u8 >) -> :: std :: result :: Result < Box < dyn :: prost_wkt :: MessageSerde > , :: prost :: DecodeError > { let mut target = Self :: default () ; :: prost :: Message :: merge (& mut target , data . as_slice ()) ? ; let erased : :: std :: boxed :: Box < dyn :: prost_wkt :: MessageSerde > = :: std :: boxed :: Box :: new (target) ; Ok (erased) } fn try_encoded (& self) -> :: std :: result :: Result < :: std :: vec :: Vec < u8 > , :: prost :: EncodeError > { let mut buf = :: std :: vec :: Vec :: with_capacity (:: prost :: Message :: encoded_len (self)) ; :: prost :: Message :: encode (self , & mut buf) ? ; Ok (buf) } } :: prost_wkt :: inventory :: submit ! { :: prost_wkt :: MessageSerdeDecoderEntry { type_url : "type.googleapis.com/SpaceX.API.Telemetron.Public.Common.TimestampInfo" , decoder : | buf : & [u8] | { let msg : TimestampInfo = :: prost :: Message :: decode (buf) ? ; Ok (:: std :: boxed :: Box :: new (msg)) } } } impl :: prost :: Name for TimestampInfo { const PACKAGE : & 'static str = "SpaceX.API.Telemetron.Public.Common" ; const NAME : & 'static str = "TimestampInfo" ; fn type_url () -> String { "type.googleapis.com/SpaceX.API.Telemetron.Public.Common.TimestampInfo" . to_string () } } } ;
