// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Status {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}

# [allow (dead_code)] const _ : () = { use :: prost_wkt :: typetag ; # [typetag :: serde (name = "type.googleapis.com/SpaceX.API.Status.Status")] impl :: prost_wkt :: MessageSerde for Status { fn package_name (& self) -> & 'static str { "SpaceX.API.Status" } fn message_name (& self) -> & 'static str { "Status" } fn type_url (& self) -> & 'static str { "type.googleapis.com/SpaceX.API.Status.Status" } fn new_instance (& self , data : Vec < u8 >) -> :: std :: result :: Result < Box < dyn :: prost_wkt :: MessageSerde > , :: prost :: DecodeError > { let mut target = Self :: default () ; :: prost :: Message :: merge (& mut target , data . as_slice ()) ? ; let erased : :: std :: boxed :: Box < dyn :: prost_wkt :: MessageSerde > = :: std :: boxed :: Box :: new (target) ; Ok (erased) } fn try_encoded (& self) -> :: std :: result :: Result < :: std :: vec :: Vec < u8 > , :: prost :: EncodeError > { let mut buf = :: std :: vec :: Vec :: with_capacity (:: prost :: Message :: encoded_len (self)) ; :: prost :: Message :: encode (self , & mut buf) ? ; Ok (buf) } } :: prost_wkt :: inventory :: submit ! { :: prost_wkt :: MessageSerdeDecoderEntry { type_url : "type.googleapis.com/SpaceX.API.Status.Status" , decoder : | buf : & [u8] | { let msg : Status = :: prost :: Message :: decode (buf) ? ; Ok (:: std :: boxed :: Box :: new (msg)) } } } impl :: prost :: Name for Status { const PACKAGE : & 'static str = "SpaceX.API.Status" ; const NAME : & 'static str = "Status" ; fn type_url () -> String { "type.googleapis.com/SpaceX.API.Status.Status" . to_string () } } } ;
