// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UtPoPLinkReport {
    #[prost(message, optional, tag = "1")]
    pub slot_timestamp: ::core::option::Option<super::common::TimestampInfo>,
    #[prost(uint32, tag = "2")]
    pub pop_id: u32,
    #[prost(uint32, tag = "3")]
    pub pop_rack_id: u32,
    #[prost(message, repeated, tag = "4")]
    pub stats: ::prost::alloc::vec::Vec<UtPoPLinkStats>,
    #[prost(string, tag = "5")]
    pub pop_version: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UtPoPLinkStats {
    #[prost(message, optional, tag = "1")]
    pub measurement_timestamp: ::core::option::Option<super::common::TimestampInfo>,
    #[prost(string, tag = "2")]
    pub ut_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub pop_rx_sdu_cnt: i64,
    #[prost(int64, tag = "4")]
    pub sdu_loss_cnt: i64,
    #[prost(uint64, tag = "5")]
    pub uplink_bytes_last_15s: u64,
    #[prost(uint64, tag = "6")]
    pub downlink_bytes_last_15s: u64,
    #[prost(uint64, tag = "7")]
    pub uplink_cplane_acl_other_violations_last_15s: u64,
}
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RateLimitReason {
    Unknown = 0,
    NoLimit = 1,
    PolicyLimit = 2,
    UserCustomLimit = 3,
    OverageLimit = 5,
}
impl RateLimitReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::NoLimit => "NO_LIMIT",
            Self::PolicyLimit => "POLICY_LIMIT",
            Self::UserCustomLimit => "USER_CUSTOM_LIMIT",
            Self::OverageLimit => "OVERAGE_LIMIT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "NO_LIMIT" => Some(Self::NoLimit),
            "POLICY_LIMIT" => Some(Self::PolicyLimit),
            "USER_CUSTOM_LIMIT" => Some(Self::UserCustomLimit),
            "OVERAGE_LIMIT" => Some(Self::OverageLimit),
            _ => None,
        }
    }
}

# [allow (dead_code)] const _ : () = { use :: prost_wkt :: typetag ; # [typetag :: serde (name = "type.googleapis.com/SpaceX.API.Telemetron.Public.Integrations.UtPoPLinkReport")] impl :: prost_wkt :: MessageSerde for UtPoPLinkReport { fn package_name (& self) -> & 'static str { "SpaceX.API.Telemetron.Public.Integrations" } fn message_name (& self) -> & 'static str { "UtPoPLinkReport" } fn type_url (& self) -> & 'static str { "type.googleapis.com/SpaceX.API.Telemetron.Public.Integrations.UtPoPLinkReport" } fn new_instance (& self , data : Vec < u8 >) -> :: std :: result :: Result < Box < dyn :: prost_wkt :: MessageSerde > , :: prost :: DecodeError > { let mut target = Self :: default () ; :: prost :: Message :: merge (& mut target , data . as_slice ()) ? ; let erased : :: std :: boxed :: Box < dyn :: prost_wkt :: MessageSerde > = :: std :: boxed :: Box :: new (target) ; Ok (erased) } fn try_encoded (& self) -> :: std :: result :: Result < :: std :: vec :: Vec < u8 > , :: prost :: EncodeError > { let mut buf = :: std :: vec :: Vec :: with_capacity (:: prost :: Message :: encoded_len (self)) ; :: prost :: Message :: encode (self , & mut buf) ? ; Ok (buf) } } :: prost_wkt :: inventory :: submit ! { :: prost_wkt :: MessageSerdeDecoderEntry { type_url : "type.googleapis.com/SpaceX.API.Telemetron.Public.Integrations.UtPoPLinkReport" , decoder : | buf : & [u8] | { let msg : UtPoPLinkReport = :: prost :: Message :: decode (buf) ? ; Ok (:: std :: boxed :: Box :: new (msg)) } } } impl :: prost :: Name for UtPoPLinkReport { const PACKAGE : & 'static str = "SpaceX.API.Telemetron.Public.Integrations" ; const NAME : & 'static str = "UtPoPLinkReport" ; fn type_url () -> String { "type.googleapis.com/SpaceX.API.Telemetron.Public.Integrations.UtPoPLinkReport" . to_string () } } } ;

# [allow (dead_code)] const _ : () = { use :: prost_wkt :: typetag ; # [typetag :: serde (name = "type.googleapis.com/SpaceX.API.Telemetron.Public.Integrations.UtPoPLinkStats")] impl :: prost_wkt :: MessageSerde for UtPoPLinkStats { fn package_name (& self) -> & 'static str { "SpaceX.API.Telemetron.Public.Integrations" } fn message_name (& self) -> & 'static str { "UtPoPLinkStats" } fn type_url (& self) -> & 'static str { "type.googleapis.com/SpaceX.API.Telemetron.Public.Integrations.UtPoPLinkStats" } fn new_instance (& self , data : Vec < u8 >) -> :: std :: result :: Result < Box < dyn :: prost_wkt :: MessageSerde > , :: prost :: DecodeError > { let mut target = Self :: default () ; :: prost :: Message :: merge (& mut target , data . as_slice ()) ? ; let erased : :: std :: boxed :: Box < dyn :: prost_wkt :: MessageSerde > = :: std :: boxed :: Box :: new (target) ; Ok (erased) } fn try_encoded (& self) -> :: std :: result :: Result < :: std :: vec :: Vec < u8 > , :: prost :: EncodeError > { let mut buf = :: std :: vec :: Vec :: with_capacity (:: prost :: Message :: encoded_len (self)) ; :: prost :: Message :: encode (self , & mut buf) ? ; Ok (buf) } } :: prost_wkt :: inventory :: submit ! { :: prost_wkt :: MessageSerdeDecoderEntry { type_url : "type.googleapis.com/SpaceX.API.Telemetron.Public.Integrations.UtPoPLinkStats" , decoder : | buf : & [u8] | { let msg : UtPoPLinkStats = :: prost :: Message :: decode (buf) ? ; Ok (:: std :: boxed :: Box :: new (msg)) } } } impl :: prost :: Name for UtPoPLinkStats { const PACKAGE : & 'static str = "SpaceX.API.Telemetron.Public.Integrations" ; const NAME : & 'static str = "UtPoPLinkStats" ; fn type_url () -> String { "type.googleapis.com/SpaceX.API.Telemetron.Public.Integrations.UtPoPLinkStats" . to_string () } } } ;
