// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnlockChallenge {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub sign_spki: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "5")]
    pub grant_keydata: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub service_keydata: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "7")]
    pub authority_grants: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartUnlockRequest {}
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartUnlockResponse {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub sign_spki: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FinishUnlockRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub challenge: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FinishUnlockResponse {
    #[prost(uint32, tag = "1")]
    pub status: u32,
}
/// Generated client implementations.
pub mod unlock_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct UnlockServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl UnlockServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> UnlockServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> UnlockServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            UnlockServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn start_unlock(
            &mut self,
            request: impl tonic::IntoRequest<super::StartUnlockRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StartUnlockResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/SpaceX.API.Device.Services.Unlock.UnlockService/StartUnlock",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "SpaceX.API.Device.Services.Unlock.UnlockService",
                        "StartUnlock",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn finish_unlock(
            &mut self,
            request: impl tonic::IntoRequest<super::FinishUnlockRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FinishUnlockResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/SpaceX.API.Device.Services.Unlock.UnlockService/FinishUnlock",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "SpaceX.API.Device.Services.Unlock.UnlockService",
                        "FinishUnlock",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}

# [allow (dead_code)] const _ : () = { use :: prost_wkt :: typetag ; # [typetag :: serde (name = "type.googleapis.com/SpaceX.API.Device.Services.Unlock.UnlockChallenge")] impl :: prost_wkt :: MessageSerde for UnlockChallenge { fn package_name (& self) -> & 'static str { "SpaceX.API.Device.Services.Unlock" } fn message_name (& self) -> & 'static str { "UnlockChallenge" } fn type_url (& self) -> & 'static str { "type.googleapis.com/SpaceX.API.Device.Services.Unlock.UnlockChallenge" } fn new_instance (& self , data : Vec < u8 >) -> :: std :: result :: Result < Box < dyn :: prost_wkt :: MessageSerde > , :: prost :: DecodeError > { let mut target = Self :: default () ; :: prost :: Message :: merge (& mut target , data . as_slice ()) ? ; let erased : :: std :: boxed :: Box < dyn :: prost_wkt :: MessageSerde > = :: std :: boxed :: Box :: new (target) ; Ok (erased) } fn try_encoded (& self) -> :: std :: result :: Result < :: std :: vec :: Vec < u8 > , :: prost :: EncodeError > { let mut buf = :: std :: vec :: Vec :: with_capacity (:: prost :: Message :: encoded_len (self)) ; :: prost :: Message :: encode (self , & mut buf) ? ; Ok (buf) } } :: prost_wkt :: inventory :: submit ! { :: prost_wkt :: MessageSerdeDecoderEntry { type_url : "type.googleapis.com/SpaceX.API.Device.Services.Unlock.UnlockChallenge" , decoder : | buf : & [u8] | { let msg : UnlockChallenge = :: prost :: Message :: decode (buf) ? ; Ok (:: std :: boxed :: Box :: new (msg)) } } } impl :: prost :: Name for UnlockChallenge { const PACKAGE : & 'static str = "SpaceX.API.Device.Services.Unlock" ; const NAME : & 'static str = "UnlockChallenge" ; fn type_url () -> String { "type.googleapis.com/SpaceX.API.Device.Services.Unlock.UnlockChallenge" . to_string () } } } ;

# [allow (dead_code)] const _ : () = { use :: prost_wkt :: typetag ; # [typetag :: serde (name = "type.googleapis.com/SpaceX.API.Device.Services.Unlock.StartUnlockRequest")] impl :: prost_wkt :: MessageSerde for StartUnlockRequest { fn package_name (& self) -> & 'static str { "SpaceX.API.Device.Services.Unlock" } fn message_name (& self) -> & 'static str { "StartUnlockRequest" } fn type_url (& self) -> & 'static str { "type.googleapis.com/SpaceX.API.Device.Services.Unlock.StartUnlockRequest" } fn new_instance (& self , data : Vec < u8 >) -> :: std :: result :: Result < Box < dyn :: prost_wkt :: MessageSerde > , :: prost :: DecodeError > { let mut target = Self :: default () ; :: prost :: Message :: merge (& mut target , data . as_slice ()) ? ; let erased : :: std :: boxed :: Box < dyn :: prost_wkt :: MessageSerde > = :: std :: boxed :: Box :: new (target) ; Ok (erased) } fn try_encoded (& self) -> :: std :: result :: Result < :: std :: vec :: Vec < u8 > , :: prost :: EncodeError > { let mut buf = :: std :: vec :: Vec :: with_capacity (:: prost :: Message :: encoded_len (self)) ; :: prost :: Message :: encode (self , & mut buf) ? ; Ok (buf) } } :: prost_wkt :: inventory :: submit ! { :: prost_wkt :: MessageSerdeDecoderEntry { type_url : "type.googleapis.com/SpaceX.API.Device.Services.Unlock.StartUnlockRequest" , decoder : | buf : & [u8] | { let msg : StartUnlockRequest = :: prost :: Message :: decode (buf) ? ; Ok (:: std :: boxed :: Box :: new (msg)) } } } impl :: prost :: Name for StartUnlockRequest { const PACKAGE : & 'static str = "SpaceX.API.Device.Services.Unlock" ; const NAME : & 'static str = "StartUnlockRequest" ; fn type_url () -> String { "type.googleapis.com/SpaceX.API.Device.Services.Unlock.StartUnlockRequest" . to_string () } } } ;

# [allow (dead_code)] const _ : () = { use :: prost_wkt :: typetag ; # [typetag :: serde (name = "type.googleapis.com/SpaceX.API.Device.Services.Unlock.StartUnlockResponse")] impl :: prost_wkt :: MessageSerde for StartUnlockResponse { fn package_name (& self) -> & 'static str { "SpaceX.API.Device.Services.Unlock" } fn message_name (& self) -> & 'static str { "StartUnlockResponse" } fn type_url (& self) -> & 'static str { "type.googleapis.com/SpaceX.API.Device.Services.Unlock.StartUnlockResponse" } fn new_instance (& self , data : Vec < u8 >) -> :: std :: result :: Result < Box < dyn :: prost_wkt :: MessageSerde > , :: prost :: DecodeError > { let mut target = Self :: default () ; :: prost :: Message :: merge (& mut target , data . as_slice ()) ? ; let erased : :: std :: boxed :: Box < dyn :: prost_wkt :: MessageSerde > = :: std :: boxed :: Box :: new (target) ; Ok (erased) } fn try_encoded (& self) -> :: std :: result :: Result < :: std :: vec :: Vec < u8 > , :: prost :: EncodeError > { let mut buf = :: std :: vec :: Vec :: with_capacity (:: prost :: Message :: encoded_len (self)) ; :: prost :: Message :: encode (self , & mut buf) ? ; Ok (buf) } } :: prost_wkt :: inventory :: submit ! { :: prost_wkt :: MessageSerdeDecoderEntry { type_url : "type.googleapis.com/SpaceX.API.Device.Services.Unlock.StartUnlockResponse" , decoder : | buf : & [u8] | { let msg : StartUnlockResponse = :: prost :: Message :: decode (buf) ? ; Ok (:: std :: boxed :: Box :: new (msg)) } } } impl :: prost :: Name for StartUnlockResponse { const PACKAGE : & 'static str = "SpaceX.API.Device.Services.Unlock" ; const NAME : & 'static str = "StartUnlockResponse" ; fn type_url () -> String { "type.googleapis.com/SpaceX.API.Device.Services.Unlock.StartUnlockResponse" . to_string () } } } ;

# [allow (dead_code)] const _ : () = { use :: prost_wkt :: typetag ; # [typetag :: serde (name = "type.googleapis.com/SpaceX.API.Device.Services.Unlock.FinishUnlockRequest")] impl :: prost_wkt :: MessageSerde for FinishUnlockRequest { fn package_name (& self) -> & 'static str { "SpaceX.API.Device.Services.Unlock" } fn message_name (& self) -> & 'static str { "FinishUnlockRequest" } fn type_url (& self) -> & 'static str { "type.googleapis.com/SpaceX.API.Device.Services.Unlock.FinishUnlockRequest" } fn new_instance (& self , data : Vec < u8 >) -> :: std :: result :: Result < Box < dyn :: prost_wkt :: MessageSerde > , :: prost :: DecodeError > { let mut target = Self :: default () ; :: prost :: Message :: merge (& mut target , data . as_slice ()) ? ; let erased : :: std :: boxed :: Box < dyn :: prost_wkt :: MessageSerde > = :: std :: boxed :: Box :: new (target) ; Ok (erased) } fn try_encoded (& self) -> :: std :: result :: Result < :: std :: vec :: Vec < u8 > , :: prost :: EncodeError > { let mut buf = :: std :: vec :: Vec :: with_capacity (:: prost :: Message :: encoded_len (self)) ; :: prost :: Message :: encode (self , & mut buf) ? ; Ok (buf) } } :: prost_wkt :: inventory :: submit ! { :: prost_wkt :: MessageSerdeDecoderEntry { type_url : "type.googleapis.com/SpaceX.API.Device.Services.Unlock.FinishUnlockRequest" , decoder : | buf : & [u8] | { let msg : FinishUnlockRequest = :: prost :: Message :: decode (buf) ? ; Ok (:: std :: boxed :: Box :: new (msg)) } } } impl :: prost :: Name for FinishUnlockRequest { const PACKAGE : & 'static str = "SpaceX.API.Device.Services.Unlock" ; const NAME : & 'static str = "FinishUnlockRequest" ; fn type_url () -> String { "type.googleapis.com/SpaceX.API.Device.Services.Unlock.FinishUnlockRequest" . to_string () } } } ;

# [allow (dead_code)] const _ : () = { use :: prost_wkt :: typetag ; # [typetag :: serde (name = "type.googleapis.com/SpaceX.API.Device.Services.Unlock.FinishUnlockResponse")] impl :: prost_wkt :: MessageSerde for FinishUnlockResponse { fn package_name (& self) -> & 'static str { "SpaceX.API.Device.Services.Unlock" } fn message_name (& self) -> & 'static str { "FinishUnlockResponse" } fn type_url (& self) -> & 'static str { "type.googleapis.com/SpaceX.API.Device.Services.Unlock.FinishUnlockResponse" } fn new_instance (& self , data : Vec < u8 >) -> :: std :: result :: Result < Box < dyn :: prost_wkt :: MessageSerde > , :: prost :: DecodeError > { let mut target = Self :: default () ; :: prost :: Message :: merge (& mut target , data . as_slice ()) ? ; let erased : :: std :: boxed :: Box < dyn :: prost_wkt :: MessageSerde > = :: std :: boxed :: Box :: new (target) ; Ok (erased) } fn try_encoded (& self) -> :: std :: result :: Result < :: std :: vec :: Vec < u8 > , :: prost :: EncodeError > { let mut buf = :: std :: vec :: Vec :: with_capacity (:: prost :: Message :: encoded_len (self)) ; :: prost :: Message :: encode (self , & mut buf) ? ; Ok (buf) } } :: prost_wkt :: inventory :: submit ! { :: prost_wkt :: MessageSerdeDecoderEntry { type_url : "type.googleapis.com/SpaceX.API.Device.Services.Unlock.FinishUnlockResponse" , decoder : | buf : & [u8] | { let msg : FinishUnlockResponse = :: prost :: Message :: decode (buf) ? ; Ok (:: std :: boxed :: Box :: new (msg)) } } } impl :: prost :: Name for FinishUnlockResponse { const PACKAGE : & 'static str = "SpaceX.API.Device.Services.Unlock" ; const NAME : & 'static str = "FinishUnlockResponse" ; fn type_url () -> String { "type.googleapis.com/SpaceX.API.Device.Services.Unlock.FinishUnlockResponse" . to_string () } } } ;
